#!/bin/bash
# This setup proxies GoAccess behind an nginx proxy for SSL
# connections. As such the address is bound to the local host.
# Furthermore nginx handles the serving of the index file which
# is generated by GoAccess.

# What this setup allows administrators to do is additionally is
# assigning a user to GoAccess making running this script safer
# and furthermore making monitoring of resources under this user
# much simpler for applications such as netdata.

# A custom log format in nginx is used to separate hosts from each
# other. As such, a custom log format here is used as well. If you
# are running a default setup: Set the format to COMBINE.

# For the GeoIP2 country database head over to the following site:
# https://dev.maxmind.com/geoip/geoip2/geolite2/

# To see everything as it is set, please view goaccess.conf.

/usr/local/bin/goaccess -p /srv/goaccess/systemd/goaccess.conf
