#!/bin/bash

GOOS=linux go build -o main && zip main.zip main && aws lambda update-function-code --function-name `printf '%s' "${PWD##*/}"` --zip-file fileb://main.zip 2>/dev/null | pwd && rm main main.zip
